# Generated by Django 4.2 on 2023-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_address_1_alter_contact_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.FileField(default='/static/nopic.png', upload_to='profile_picture'),
        ),
    ]
