# Generated by Django 4.2 on 2023-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(default='static/nopic.png', upload_to='profile_picture'),
        ),
    ]
