# Generated by Django 4.2 on 2023-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(default='static/nopic.png', null=True, upload_to='media/profile_pics'),
        ),
    ]
